### ISSUE TITLE
Page # textbox is converting to string

### ISSUE THREAD

**Issue by hornetnz** [MyPureCloud/fixtable-ember#102]
Just found that if you click inside the page # textbox and then click the next page button, it's treating the textbox value as a string and adding 1. So if you're on page 1, it'll go to 11, and then 111 (if it exists). The problem doesnt appear to be an issue clicking on the previous page button.

If anyone else can confirm this, please do.

![edit](https://user-images.githubusercontent.com/1258688/28577862-f2e64dfe-7125-11e7-843c-c0e5da89c73c.gif)

**Comment by rbrcurtis** [comment]
@hornetnz does this only happen if you click into the field first?

**Comment by hornetnz** [comment]
Correct. As shown in the gif. Clicking just the arrow goes from 11 => 12. Then box to arrow goes 12 => 51 (my max page #)

**Comment by smargovsky** [comment]
Addressed by https://github.com/MyPureCloud/fixtable-ember/pull/103 - Thanks @hornetnz!
