### ISSUE TITLE
Debounce the notification that the current page has changed

### ISSUE THREAD

**Issue by menewman** [MyPureCloud/fixtable-ember#27]
For server-side pagination in particular, it is unnecessarily expensive to notify that the page has changed after every keystroke when the user is typing into the "current page" input. This will effectively lead to an AJAX call after every keystroke.

I don't see this as very high priority, although it would be good to fix it. Fixtable-Angular behaves this way too, and the issue is entirely avoided if the user uses the previous / forward pager controls.

An alternative to debouncing would be waiting until focus leaves the input before changing the current page. This can feel a little less responsive (especially if client-side pagination is on, in which case re-paginating after each keystroke is relatively cheap), but the advantage is that we won't make changes until we're pretty confident that the user is done typing.

**Comment by smargovsky** [comment]
Part of https://github.com/MyPureCloud/fixtable-ember/pull/99
