### ISSUE TITLE
Add support for custom filter types

### ISSUE THREAD

**Issue by menewman** [MyPureCloud/fixtable-ember#29]
Currently we only allow two kinds of filters: search (which is a "contains"-type filter) and select (which is an equality filter). We could also let the user define custom filter types; Fixtable-Angular appears to already have this functionality.

For now, not high priority because I can't think of a good use case (search & select should cover the vast majority of use cases). Just wanted to document this feature since the Angular version has it.

**Comment by smargovsky** [comment]
👍
