### ISSUE TITLE
Add support for labels on select-type filters

### ISSUE THREAD

**Issue by sivamahadevan** [MyPureCloud/fixtable-ember#52]
On fixtable-angular, I noticed that for each object in the "selectOptions" field of the filter column, you could optionally add a "label" field. In my application, I need to show the user a string for an option but actually send a filter request with a different value. For instance, I want to show the user options for "true" and "false", but I want the filter request to be for the values 1 and 0 respectively.

**Comment by menewman** [comment]
This is a good enhancement request that would be fairly simple to implement. I'm open to a PR if you want to submit one. Otherwise, I might be able to find some time to knock this out later. :)

**Comment by sivamahadevan** [comment]
I can submit this one, thanks!

**Comment by sivamahadevan** [comment]
#53 - please check this PR and let me know if it's okay.

**Comment by menewman** [comment]
@sivamahadevan -- Thanks for submitting this. I'm taking a look now.
