### ISSUE TITLE
Filters: Add placeholder

### ISSUE THREAD

**Issue by smargovsky** [MyPureCloud/fixtable-ember#72]
Add the ability to specify placeholder text for filter inputs and selects

**Comment by menewman** [comment]
Reasonable request. Ideally the column definition for this would look like this:

```
[
  {
    key: 'name',
    header: 'Name',
    filter: {
      type: 'search',
      placeholder: 'Enter a name'
    }
  }
]
```

Would this really be necessary for select-type filters? HTML selects don't generally have placeholders.
