### ISSUE TITLE
Cannot find module 'broccoli-funnel' and 'broccoli-merge-trees'

### ISSUE THREAD

**Issue by sivamahadevan** [MyPureCloud/fixtable-ember#74]
I recently upgraded from 0.1.x to the latest stable version and I could not run my ember project because of these missing npm modules. I noticed that they are there in this project's devDependencies, should they be in dependencies instead? index.js requires these modules.

**Comment by menewman** [comment]
No, I don't think these particular packages should need to be in `dependencies`. After upgrading, have you tried the following steps?

```bash
npm cache clean
bower cache clean
rm -rf node_modules bower_components dist tmp
npm install
bower install
```

**Comment by sivamahadevan** [comment]
I tried this and it didn't install these two dev dependencies. After running `npm install`, I checked the /node_modules/fixtable-ember folder and its own node_modules folder and the only thing that was installed is font-awesome. My local NODE_ENV is set to development and all other packages install correctly.

**Comment by menewman** [comment]
What are your node and npm versions? Are you consuming fixtable-ember inside of another addon, or from a regular Ember app?

**Comment by sivamahadevan** [comment]
I'm on Node 4.4.5 and NPM 2.15.5. I'm consuming fixtable-ember from inside a regular Ember app. If it helps, I've also tried removing fixtable-ember from my bower.json and package.json, removing the folder from my node_modules, and running `ember install fixtable-ember` from the project root; however, before this command succeeds, it returns with the error "cannot find modules broccoli-funnel and broccoli-merge-trees".

**Comment by menewman** [comment]
Gotcha. Unfortunately, I believe that NPM 3+ is required for these dependencies to work correctly. You could try using a version prior to 1.0.2 -- I believe version 1.0.0 does not include those dependencies. But that shuts off the upgrade path for you until you upgrade NPM.

**Comment by sivamahadevan** [comment]
Thanks for your help! Other than a few deprecation warnings, 1.0.0 works well for our use.
