### ISSUE TITLE
Client-side sorting doesn't work on ember objects

### ISSUE THREAD

**Issue by sivamahadevan** [MyPureCloud/fixtable-ember#77]
https://github.com/MyPureCloud/fixtable-ember/blob/fcfd1416eb11b5ebda800c2bbf1e60d34a7bcefd/addon/components/fixtable-grid.js#L135

Similar to #70, client-side sorting currently only works for POJOs since each datarow's field is accessed using the [] operator.

**Comment by menewman** [comment]
Thanks, @sivamahadevan. The fix should be more-or-less the same as what we did in PR #58.

**Comment by sivamahadevan** [comment]
No problem, I can submit a PR for this soon.

**Comment by menewman** [comment]
@sivamahadevan - No need to submit a PR; this will be addressed in PR #78. :)

**Comment by sivamahadevan** [comment]
Sounds good!
