### ISSUE TITLE
font-awesome not imported in when fixtable-ember is nested in addons > ember-cli 2.12

### ISSUE THREAD

**Issue by omarestrella** [MyPureCloud/fixtable-ember#94]
The error you get when running `ember server` in an app that includes an addon that uses fixtable-ember is:
```
ENOENT: no such file or directory, scandir '/Users/omarestrella/Development/orgspan/dummy-app/node_modules/dummy-addon/node_modules/fixtable-ember/node_modules/font-awesome/fonts'
```

You can recreate the issue by creating a dummy app and dummy addon, installing ember-fixtable in the dummy addon (inside `dependencies`), putting the addon in the package.json and linking the addon to the app, and running `ember server`.

There should probably be a distinction between the root app and the parent so that the correct node_modules path is used. For example:
```
let rootApp = app;
while (rootApp.app) {
  rootApp = rootApp.app;
}

let parent = app;
while (parent.parent) {
  parent = parent.parent;
}
```

And you can use `parent.nodeModulesPath` for the correct path and the `rootApp.import` for importing the CSS that is being imported.

**Comment by smargovsky** [comment]
Not reproducible consistently - generally when I've seen this, it's due to a dependency version mismatch somewhere in the tree.  Though we should look into making sure our imports are up to snuff in regard to nesting, addons, and engines ( again! ).
