### ISSUE TITLE
Add a observed property to allow externally triggered reload

### ISSUE THREAD

**Issue by git-moe** [MyPureCloud/fixtable-ember#95]
There are always cases when we need to apply filter that either are not displayed in the fixtable-grid, or would make more sense to be triggered through another on-screen or off screen action. However, currently the notifyReloadContent() is only called when the page / filter / sort changes.

As the action of notifyReloadContent exists outside of the componment, we can modify the query call and add all kinds of filter to our hearts content, but we lack a way to trigger the grid reload.

If we can setup a observed property that would call the notifyReloadContent and trigger the grid reload, we can easily set up all kind of custom filters without additional effort from fixtable-ember side.  All we need to do is to setup the appropriate filter in the onReloadContent action, and change the observed property to trigger the grid-reload. 

Would that sound like a good enough trade off to break the component isolation? All we need is a easy way to trigger reload externally, and this could potentially make it quite a bit more powerful..

**Comment by menewman** [comment]
Given that this component already has support for custom filter components, it really doesn't seem like it's worth breaking its encapsulation (and Ember's DDAU philosophy) to support niche filtering use cases. The consumer of this component will always able to change the underlying data used by the fixtable-grid without needing to trigger anything at all, since it owns the data, right?

**Comment by git-moe** [comment]
That does provide solution when the property I am filtering on is inside the grid and. However, there are cases when I we are trying to filter on property that is outside of the grid. If I need to filter on a property that is outside the grid, this would mean I need to make an additional grid to implement this, and then try to hide that column. Also does not sound like a clean way to handle this either.. 

I guess this ends up to be a choice. Should I have an additional column that I dont display in the grid to trigger reload, or do we want to have one separate property that is only used for trigger reload. 

I am leaning more toward separate property as it could make implementing complicated chain select quite a bit easier. ( those Year > Brand > Model type),  But I can understand if you think otherwise.

**Comment by menewman** [comment]
> I am leaning more toward separate property as it could make implementing grids that shows different content based on user role quite a bit easier. (like Admin see everything while user see their own stuff only, but you don't really want the user field to be in the grid)

In this example, depending on whether you're trying to hide rows or columns from the non-admin, you could do the following:
- If you're trying to hide rows, then you should just have your data-loading code not return the additional rows for non-admins. No need to trigger anything on the grid component.
- If you're trying to hide columns, then you should define a different grid with different column definitions and show that one instead. Again, no need to trigger anything.

**Comment by git-moe** [comment]
In my case fixtable-grid is my data-loading code as I am doing server side paging / filter / sorting. Hence the need of injecting additional filter.
There is a UI toggle that allows user to switch between own entry and all entry, and that checkbox is designed to sit outside of the grid.  I currently tries to call the onReloadContent action again, and supply previously cached pageSize / pageNumber / filter / sortObject (also modify the filter as checkbox changes) to complete the call.  The idea of having a external trigger comes in as it would eliminates the need of caching those arguments, which are only fixtable related. 

I can imagine a few other use cases of externally triggered refresh could come in handy ( server side chain select? Real-time updated something? ). But if this is not something you find necessary to add into the component I understand.

**Comment by smargovsky** [comment]
> There is a UI toggle that allows user to switch between own entry and all entry, and that checkbox is designed to sit outside of the grid.

We had a similar case that we solved via a custom filter.  The other solution, as @menewman suggests above, is to have separate tables that are displayed as the checkbox value changes.  Finally, and this feels a bit hacky, but you can tie any property value from fixtable to your own context. 

Example: I needed to influence the `currentPage` that Fixtable Ember displayed based on actions outside of the addon.  So, `{{fixtable-grid ... currentPage=myCurrentPage ...}}`  In your case, you could try the same w/ `filters` array.  I know, dirty...but it works 😜

**Comment by git-moe** [comment]
I end up storing the paging / sorting / filtering arguments into the parent component, and call the onReloadContent action directly. 

Thanks for the suggestion and for the great component!

**Comment by smargovsky** [comment]
Glad you found a solution.  Closing this issue.
