### ISSUE TITLE
extra arrow appears when column is sorted in descending order

### ISSUE THREAD

**Issue by pmoaddel** [MyPureCloud/fixtable-ember#96]
![image](https://cloud.githubusercontent.com/assets/11447714/26329142/6a87e3a6-3f0b-11e7-8d03-a9da87722dd0.png)

**Comment by smargovsky** [comment]
@pmoaddel - the only CSS `fixtable-ember` adds to sorted columns is a span w/ class `caret`.  This looks like a problem w/ your specific implementation.  Hit me up dog, we can take a look if this is still a problem.
